[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
[context.production.environment]
  API_URL = "https://api.adviseren.erkenningen.nl/graphql"
  DNN_URL = "https://adviseren.erkenningen.nl"
[context.deploy-preview.environment]
  API_URL = "https://XXapi.adviseren.erkenningen.nl/graphql"
  DNN_URL = "https://XXadviseren.erkenningen.nl"
