backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  # - name: "blog"
  #   label: "Blog"
  #   folder: "src/pages/blog"
  #   create: true
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  #   fields:
  #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Description", name: "description", widget: "text"}
  #     - {label: "Body", name: "body", widget: "markdown"}
  #     - {label: "Tags", name: "tags", widget: "list"}
  - name: "Wat-wij-doen"
    label: "Wat wij doen"
    folder: "src/pages/wat-wij-doen"
    create: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Wat-wij-doen/licentiehouders"
    label: "Licentiehouders"
    folder: "src/pages/wat-wij-doen/licentiehouders"
    create: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Wat-wij-doen/kennisaanbieders"
    label: "Kennisaanbieders"
    folder: "src/pages/wat-wij-doen/kennisaanbieders"
    create: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Wat-wij-doen/exameninstellingen"
    label: "Exameninstellingen"
    folder: "src/pages/wat-wij-doen/exameninstellingen"
    create: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Wat-wij-doen/KBA-GB-gecertificeerde-bedrijven"
    label: "KBA-GB gecertificeerde bedrijven"
    folder: "src/pages/wat-wij-doen/KBA-GB-gecertificeerde-bedrijven"
    create: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Wat-wij-doen/formulieren"
    label: "Formulieren"
    folder: "src/pages/wat-wij-doen/formulieren"
    create: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Wat-wij-doen/brochures"
    label: "Brochures"
    folder: "src/pages/wat-wij-doen/brochures"
    create: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "Licenties"
    label: "Licenties"
    folder: "src/pages/licenties"
    create: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Bijeenkomsten"
    label: "Bijeenkomsten"
    folder: "src/pages/bijeenkomsten"
    create: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      # - file: "src/pages/about/index.md"
      #   label: "About"
      #   name: "about"
      #   fields:
      #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
      #     - {label: "Title", name: "title", widget: "string"}
      #     - {label: "Body", name: "body", widget: "markdown"}
#      - file: "src/pages/wat-wij-doen/index.md"
#        label: "Wat wij doen"
#        name: "wat-wij-doen"
#        fields:
#          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
#          - {label: "Title", name: "title", widget: "string"}
#          - {label: "Path", name: "path", widget: "string"}
#          - {label: "Body", name: "body", widget: "markdown"}
      # - file: "src/pages/products/index.md"
      #   label: "Products Page"
      #   name: "products"
      #   fields:
      #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
      #     - {label: Title, name: title, widget: string}
      #     - {label: Image, name: image, widget: image}
      #     - {label: Heading, name: heading, widget: string}
      #     - {label: Description, name: description, widget: string}
      #     - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
      #     - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      #     - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
      #     - {label: Full_image, name: full_image, widget: image}
      #     - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      # - file: "src/pages/wat-wij-doen/index.md"
      #   label: "Wat wij doen Page"
      #   name: "wat-wij-doen"
      #   fields:
      #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "links-page"}
      #     - {label: Title, name: title, widget: string}
      #     - {label: Heading, name: heading, widget: string}
      #     - {label: Description, name: description, widget: string}
