backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  # - name: "Wat-wij-doen"
  #   label: "Wat wij doen"
  #   folder: "src/pages/wat-wij-doen"
  #   create: false
  #   delete: false
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Body", name: "body", widget: "markdown" }
  - name: "Wat-wij-doen"
    label: "Wat-wij-doen"
    files:
      - file: "src/pages/wat-wij-doen/index.md"
        label: "Wat wij doen - index"
        name: "wat-wij-doen"
        delete: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "wat-wij-doen-bureau-erkenningen"
    label: "Wat-wij-doen/Bureau Erkenningen"
    folder: "src/pages/wat-wij-doen/bureau-erkenningen"
    create: true
    delete: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "wat-wij-doen-licentiehouders"
    label: "Wat-wij-doen/licentiehouders"
    folder: "src/pages/wat-wij-doen/licentiehouders"
    create: true
    delete: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "wat-wij-doen-kennisaanbieders"
    label: "Wat-wij-doen/kennisaanbieders"
    folder: "src/pages/wat-wij-doen/kennisaanbieders"
    create: true
    delete: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "wat-wij-doen-exameninstellingen"
    label: "Wat-wij-doen/exameninstellingen"
    folder: "src/pages/wat-wij-doen/exameninstellingen"
    create: true
    delete: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "wat-wij-doen-KBA-GB-gecertificeerde-bedrijven"
    label: "Wat-wij-doen/KBA-GB-gecertificeerde-bedrijven"
    folder: "src/pages/wat-wij-doen/KBA-GB-gecertificeerde-bedrijven"
    create: true
    delete: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "wat-wij-doen-formulieren"
    label: "Wat-wij-doen/Formulieren"
    folder: "src/pages/wat-wij-doen/formulieren"
    create: true
    delete: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "brochures"
    label: "Wat-wij-doen/Brochures"
    folder: "src/pages/wat-wij-doen/brochures"
    create: true
    delete: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "Licenties"
    label: "Licenties"
    folder: "src/pages/licenties"
    create: false
    delete: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "Licenties-licentie-aanvragen"
    label: "Licenties/licentie-aanvragen"
    folder: "src/pages/licenties/licentie-aanvragen"
    create: true
    delete: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "Licenties-welke-licenties-zijn-er"
    label: "Licenties/welke-licenties-zijn-er"
    folder: "src/pages/licenties/welke-licenties-zijn-er"
    create: true
    delete: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "Licenties-wetten-en-regels"
    label: "Licenties/wetten-en-regels"
    folder: "src/pages/licenties/wetten-en-regels"
    create: true
    delete: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "Bijeenkomsten"
    label: "Bijeenkomsten"
    folder: "src/pages/bijeenkomsten"
    create: false
    delete: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "mijn-bureau-erkenningen"
    label: "Mijn Bureau Erkenningen"
    folder: "src/pages/mijn-bureau-erkenningen"
    create: true
    delete: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "home-footer"
    label: "Home en Footer"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "home"
        delete: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/contact.md"
        label: "Contact"
        name: "contact"
        delete: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
