backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  # - name: "Wat-wij-doen"
  #   label: "Wat wij doen"
  #   folder: "src/pages/wat-wij-doen"
  #   create: false
  #   delete: false
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Body", name: "body", widget: "markdown" }
  - name: "Wat-wij-doen"
    label: "Wat-wij-doen"
    files:
      - file: "src/pages/wat-wij-doen/index.md"
        label: "Wat wij doen - index"
        name: "wat-wij-doen"
        delete: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/wat-wij-doen/bureau-erkenningen/be-app.md"
        label: "BE app"
        name: "BE app"
        delete: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/wat-wij-doen/bureau-erkenningen/index.md"
        label: "Bureau Erkenningen"
        name: "Bureau Erkenningen"
        delete: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "src/pages/wat-wij-doen/licentiehouders/index.md"
        label: "Licentiehouders"
        name: "Licentiehouders"
        delete: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "src/pages/wat-wij-doen/kennisaanbieders/index.md"
        label: "Kennisaanbieders - index"
        name: "Kennisaanbieders - index"
        delete: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/wat-wij-doen/kennisaanbieders/bijeenkomst-organiseren.md"
        label: "Kennisaanbieders/bijeenkomst-organiseren"
        name: "kennisaanbieders-bijeenkomst-organiseren"
        delete: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/wat-wij-doen/kennisaanbieders/kennisaanbieder-worden.md"
        label: "Kennisaanbieders/kennisaanbieder-worden"
        name: "kennisaanbieders-kennisaanbieder-worden"
        delete: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  # - name: "Wat-wij-doen/bureau-erkenningen/licentiehouders"
  #   label: "Wat-wij-doen/bureau-erkenningen/licentiehouders"
  #   files:
  #     - file: "Wat-wij-doen/licentiehouders/index.md"
  #       label: "Wat wij doen/Licentiehouders/index"
  #       delete: false
  #       fields:
  #         - { label: "Title", name: "title", widget: "string" }
  #         - { label: "Body", name: "body", widget: "markdown" }
  # - name: "Wat-wij-doen/kennisaanbieders"
  #   label: "Wat wij doen/Kennisaanbieders"
  #   files:
  #     - file: "Wat-wij-doen/kennisaanbieders/index.md"
  #       label: "Wat wij doen/kennisaanbieders/index"
  #       delete: false
  #       fields:
  #         - { label: "Title", name: "title", widget: "string" }
  #         - { label: "Body", name: "body", widget: "markdown" }
  #     - file: "Wat-wij-doen/kennisaanbieders/bijeenkomst-organiseren.md"
  #       label: "Wat wij doen/kennisaanbieders/bijeenkomst-organiseren"
  #       delete: false
  #       fields:
  #         - { label: "Title", name: "title", widget: "string" }
  #         - { label: "Body", name: "body", widget: "markdown" }
  #     - file: "Wat-wij-doen/kennisaanbieders/kennisaanbieder-worden.md"
  #       label: "Wat wij doen/kennisaanbieders/kennisaanbieder-worden"
  #       delete: false
  #       fields:
  #         - { label: "Title", name: "title", widget: "string" }
  #         - { label: "Body", name: "body", widget: "markdown" }
  # - name: "Wat-wij-doen/exameninstellingen"
  #   label: "Wat wij doen/Exameninstellingen"
  #   folder: "src/pages/wat-wij-doen/exameninstellingen"
  #   create: false
  #   delete: false
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Body", name: "body", widget: "markdown" }
  # - name: "Wat-wij-doen/KBA-GB-gecertificeerde-bedrijven"
  #   label: "Wat wij doen/KBA-GB gecertificeerde bedrijven"
  #   folder: "src/pages/wat-wij-doen/KBA-GB-gecertificeerde-bedrijven"
  #   create: false
  #   delete: false
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Body", name: "body", widget: "markdown" }
  # - name: "Wat-wij-doen/formulieren"
  #   label: "Wat wij doen/Formulieren"
  #   folder: "src/pages/wat-wij-doen/formulieren"
  #   create: false
  #   delete: false
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Body", name: "body", widget: "markdown" }
  # - name: "Wat-wij-doen/brochures"
  #   label: "Wat wij doen/Brochures"
  #   folder: "src/pages/wat-wij-doen/brochures"
  #   create: false
  #   delete: false
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Body", name: "body", widget: "markdown" }

  - name: "Licenties"
    label: "Licenties"
    folder: "src/pages/licenties"
    create: false
    delete: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "Bijeenkomsten"
    label: "Bijeenkomsten"
    folder: "src/pages/bijeenkomsten"
    create: false
    delete: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Overige pagina's"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "home"
        delete: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/contact.md"
        label: "Contact"
        name: "contact"
        delete: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/wat-wij-doen/licentiehouders/index.md"
        label: "Licentiehouders"
        name: "licentiehouders"
        delete: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
# - file: "src/pages/about/index.md"
#   label: "About"
#   name: "about"
#   fields:
#     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
#     - {label: "Title", name: "title", widget: "string"}
#     - {label: "Body", name: "body", widget: "markdown"}
#      - file: "src/pages/wat-wij-doen/index.md"
#        label: "Wat wij doen"
#        name: "wat-wij-doen"
#        fields:
#          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
#          - {label: "Title", name: "title", widget: "string"}
#          - {label: "Path", name: "path", widget: "string"}
#          - {label: "Body", name: "body", widget: "markdown"}
# - file: "src/pages/products/index.md"
#   label: "Products Page"
#   name: "products"
#   fields:
#     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
#     - {label: Title, name: title, widget: string}
#     - {label: Image, name: image, widget: image}
#     - {label: Heading, name: heading, widget: string}
#     - {label: Description, name: description, widget: string}
#     - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
#     - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
#     - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
#     - {label: Full_image, name: full_image, widget: image}
#     - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
# - file: "src/pages/wat-wij-doen/index.md"
#   label: "Wat wij doen Page"
#   name: "wat-wij-doen"
#   fields:
#     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "links-page"}
#     - {label: Title, name: title, widget: string}
#     - {label: Heading, name: heading, widget: string}
#     - {label: Description, name: description, widget: string}
